language:
  - "node_js"

node_js:
  - "7.5"

script:
  - npm test

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: "TKQq39u5WjpmxUTJLZRU9puQscf5ukfXZSL518nzUjIMsRasUaSzlBA9aS7Rzx4EXmeJLOlrXQiyLCpVzRzKnniOKeDQzi2bdF0w/U8rs9ZmzS0HAF3pnG8pY7xqy3ehDgHYySIjfn+8Jm6kxHYVmilKoQaIk/3bpS60aYQCNATYVz39/lF3TvO+weASXB5MWSZguZ1dk/LUp7YOqrEzmrs42g0XLqVlqz1rgcXhHXmUwFUxfuNcyOhFMQdtGGbDBgvg0PuDle0PXP5/YeJTojiyWYfX5yam3exp+bfeyPi3MIeki8ISYilY9BC0cTnr0gHaFxFf4ruj1EpdAWvTs5JmJdKYDeKd3P734ZVuu4AQbE/+8O5mLl35Jt0OU8kk8AzvcCIwaWhnGQKmXCFtfpi9nhaCRNKUixq575x1Jge+Bbg7obT93sFPmqLVsZb50pUogxMMMyxAFt5J6ydC4exipdnn1/myClzYLZDdfL6qbp8aVX/ZA2BE0JImZ280aqbQca+kGlFHdDw62TkkBXnQcwlGmO6zI1adfft6EuvyrCUxSktmqvMRoH0WmvJh3BOr1QMQ1KgmIv2d3u7ImJt0MfOBllhtaZ2OPZQz8Tuu239eOMvNJIupbbMAtoidmObCrxmVQUFE0Z3eWTQZkErPeeQQbj3yOrNHhvcJWa8="
